### ISSUE TITLE
crash on samsung galaxy s3 os 4.1.1 ---------> Multistatetogglebutton example project 

### ISSUE THREAD

**Issue by aitbaali** [jlhonora/multistatetogglebutton#14]
12-14 21:56:38.039 13295-13295/org.honorato.multistatetogglebuttonexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{org.honorato.multistatetogglebuttonexample/org.honorato.multistatetogglebuttonexample.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                at android.os.Looper.loop(Looper.java:137)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                                             Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
                                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                                                at org.honorato.multistatetogglebuttonexample.MainActivity.onCreate(MainActivity.java:15)
                                                                                                at android.app.Activity.performCreate(Activity.java:5008)
                                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                at android.os.Looper.loop(Looper.java:137) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                                at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                                at org.honorato.multistatetogglebuttonexample.MainActivity.onCreate(MainActivity.java:15) 
                                                                                                at android.app.Activity.performCreate(Activity.java:5008) 
                                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                at android.os.Looper.loop(Looper.java:137) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                                             Caused by: android.content.res.Resources$NotFoundException: File res/drawable/button_not_pressed.xml from drawable resource ID #0x7f020046
                                                                                                at android.content.res.Resources.loadDrawable(Resources.java:1918)
                                                                                                at android.content.res.Resources.getDrawable(Resources.java:659)
                                                                                                at android.view.View.setBackgroundResource(View.java:14179)
                                                                                                at android.support.v7.widget.AppCompatButton.setBackgroundResource(AppCompatButton.java:75)
                                                                                                at org.honorato.multistatetogglebutton.MultiStateToggleButton.setButtonState(MultiStateToggleButton.java:259)
                                                                                                at org.honorato.multistatetogglebutton.MultiStateToggleButton.setElements(MultiStateToggleButton.java:143)
                                                                                                at org.honorato.multistatetogglebutton.MultiStateToggleButton.<init>(MultiStateToggleButton.java:49)
                                                                                                at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                                at org.honorato.multistatetogglebuttonexample.MainActivity.onCreate(MainActivity.java:15) 
                                                                                                at android.app.Activity.performCreate(Activity.java:5008) 
                                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                at android.os.Looper.loop(Looper.java:137) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                                             Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                                at android.content.res.TypedArray.getColor(TypedArray.java:326)
                                                                                                at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:951)
                                                                                                at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
                                                                                                at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
                                                                                                at android.content.res.Resources.loadDrawable(Resources.java:1915)
                                                                                                at android.content.res.Resources.getDrawable(Resources.java:659) 
                                                                                                at android.view.View.setBackgroundResource(View.java:14179) 
                                                                                                at android.support.v7.widget.AppCompatButton.setBackgroundResource(AppCompatButton.java:75) 
                                                                                                at org.honorato.multistatetogglebutton.MultiStateToggleButton.setButtonState(MultiStateToggleButton.java:259) 
                                                                                                at org.honorato.multistatetogglebutton.MultiStateToggleButton.setElements(MultiStateToggleButton.java:143) 
                                                                                                at org.honorato.multistatetogglebutton.MultiStateToggleButton.<init>(MultiStateToggleButton.java:49) 
                                                                                                at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                                at org.honorato.multistatetogglebuttonexample.MainActivity.onCreate(MainActivity.java:15) 
                                                                                                at android.app.Activity.performCreate(Activity.java:5008) 
                                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                at android.os.Looper.loop(Looper.java:137) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by jlhonora** [comment]
Thanks for reporting this. Did you try running the example or using the library in your own app? Is there any code you can share? Are you using ProGuard by any chance?

**Comment by aitbaali** [comment]
I just run the example with android studio, my device is genymotion

**Comment by jlhonora** [comment]
I just updated the library. It was being caused by a bug in Android: https://code.google.com/p/android/issues/detail?id=26251

Please try again and let me know if it works (already tried it in an S2, but just in case).

**Comment by aitbaali** [comment]
thanks @jlhonora , it works like a charm, your last update fixed the bug :+1:

**Comment by jlhonora** [comment]
Thanks a lot for your help. Please let me know if you run into any other issues or if you have improvement ideas.

**Comment by vipulraut** [comment]
Hi 

I am getting following issue
android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton

On MI Note 3 ,Android 6.0.1 API 23 device. 
Any idea on this issue?
