### ISSUE TITLE
Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton on API 19

### ISSUE THREAD

**Issue by raccoon4me** [jlhonora/multistatetogglebutton#27]
Hi there :)

First of all, thanks a lot for your multi toggle button, very much appreciated :) It works perfectly on API 21, but it fails to work on API 19 (4.4.4).

```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.gta.fab1, PID: 14002 android.view.InflateException: Binary XML file line #42: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                          at com.example.gta.fab1.adapter.ADWhereFragmentConfirmation.getView(ADWhereFragmentConfirmation.java:61)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2255)
                                                                          at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
                                                                          at android.widget.ListView.onMeasure(ListView.java:1175)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1560)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:664)
                                                                          at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                          at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1149)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:729)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                          at android.view.View.measure(View.java:16497)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
```

I'm using it in a ListView with a Custom Adapter, there is the code of my CustomAdapter
```java
package com.example.gta.fab1.adapter;
import android.app.Activity;
import android.content.Context;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.Button;
import android.widget.TextView;

import com.example.gta.fab1.R;
import com.example.gta.fab1.model.RowItemWhereFragment;

import org.honorato.multistatetogglebutton.MultiStateToggleButton;
import org.honorato.multistatetogglebutton.ToggleButton;

import java.util.List;

public class ADWhereFragmentConfirmation extends BaseAdapter {

    Context context;
    List<RowItemWhereFragment> rowItem;

    public ADWhereFragmentConfirmation(Context context, List<RowItemWhereFragment> rowItem) {
        this.context = context;
        this.rowItem = rowItem;
    }

    @Override
    public int getCount() {

        return rowItem.size();
    }

    @Override
    public Object getItem(int position) {

        return rowItem.get(position);
    }

    @Override
    public long getItemId(int position) {

        return rowItem.indexOf(getItem(position));
    }
    
    @Override
    public boolean isEnabled(int position) {
        return false;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {

        if (convertView == null) {
            LayoutInflater mInflater = (LayoutInflater) context
                    .getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
            convertView = mInflater.inflate(R.layout.custom_layout_invitation_restaurant, null);
        }

        TextView txtTitle = (TextView) convertView.findViewById(R.id.title);
        TextView txtAddress = (TextView) convertView.findViewById(R.id.address);

        RowItemWhereFragment row_pos = rowItem.get(position);

        txtTitle.setText(row_pos.getTitle());
        txtAddress.setText(row_pos.getAddress());

        final MultiStateToggleButton button = (MultiStateToggleButton) convertView.findViewById(R.id.mstb_multi_id);
        button.setTag(position);
        button.setOnValueChangedListener(new ToggleButton.OnValueChangedListener() {
            @Override
            public void onValueChanged(int position) {
                System.out.println(button.getTag()+"<>"+position);
            }
        });
        return convertView;
    }
}
```

It seems to complain about line 61:

```
convertView = mInflater.inflate(R.layout.custom_layout_invitation_restaurant, null);
```

May be i'm doing something wrong, but the very same code works nicely on API 21, do you think you could take a look at it please ?

Thanks a lot in advance
Kind Regards

Steve

**Comment by jlhonora** [comment]
How about trying with `LayoutInflater.from(this.getContext())`? I'm not sure if it solves the issue, but it could help.

Do you have a complete sample you can share?

**Comment by raccoon4me** [comment]
Hi jlhonora, 

Thanks for your answer, i'm a little bit in rush today, but tomorrow i will delete some part and i push to github, so you can compile it and see what could be the cause.

Thanks a lot 

Steve

**Comment by raccoon4me** [comment]
Hola Jose,

Pues, estaba a punto de enviarte une parte de mi applicacion donde habia el
problema, pero hoy esta funcionando guay.
Joder, es q este tipo de errora me pone nervioso :) No entiendo por q hoy
funciona bien i ayer no :@ :/

Pues nada, lo siento mucho. Voy a cerrar ahora mismo la tarea en github.

Un saludo i muchas gracias para haber creado este libraria

Steve

ps: perdona mi espanol, hace tiempo q no vivo en espana :P

**Comment by jlhonora** [comment]
Hola Steve, no hay problema! Tu español está bastante bien :) Switching to english now in case someone else stumbles with this problem.

I'm glad it's working now. I do recommend using `LayoutInflater.from(this.getContext())` to get the `LayoutInflater` instance instead of the one you're using. Using `Activity.LAYOUT_INFLATER_SERVICE` seems a bit odd since you're not calling it from an Activity, but from an Adapter. 

Let me know if the error surfaces back.
